// Arquivo centralizado de ícones para manter consistência
import { Flame, Gem, ShoppingCart, Sword, Star, User, Wallet, Package, Trophy, Settings, Lock, Zap, Target, Crown, Shield, Award, Gift, Heart, ThumbsUp, CheckCircle, AlertCircle, Info, Clock, Calendar, Mail, Phone, MapPin, Home, Search, Filter, Plus, Minus, Edit, Trash2, Eye, EyeOff, Download, Upload, Share, Copy, ExternalLink, ArrowRight, ArrowLeft, ChevronRight, ChevronLeft, ChevronUp, ChevronDown, X, Menu, MoreHorizontal, Play, Pause, Volume2, VolumeX, Wifi, WifiOff, Battery, BatteryLow, Signal, Bluetooth, Camera, Image, Video, Music, Headphones, Mic, MicOff, Bell, BellOff, MessageCircle, MessageSquare, Send, Bookmark, BookmarkCheck, Flag, Tag, Tags, Folder, FolderOpen, File, FileText, FileImage, FileVideo, Database, Server, Cloud, DownloadCloud as CloudDownload, UploadCloud as CloudUpload, Wifi as Network, Globe, Link, Unlink, RefreshCw as Refresh, RotateCcw, RotateCw, Maximize, Minimize, Square, Circle, Triangle, Hexagon, Octagon, Diamond, Sparkles, Gamepad2 } from "lucide-react";

// Exportar ícones mais usados
export {
  // Principais
  Flame,
  Gem,
  ShoppingCart,
  Sword,
  Star,
  User,
  Wallet,
  Package,
  Trophy,
  Settings,
  Lock,
  Zap,
  Target,
  Crown,
  Shield,
  Award,
  Gift,
  Heart,
  ThumbsUp,
  CheckCircle,
  AlertCircle,
  Info,
  Clock,
  Calendar,
  Mail,
  Phone,
  MapPin,
  Home,
  Search,
  Filter,
  Plus,
  Minus,
  Edit,
  Trash2,
  Eye,
  EyeOff,
  Download,
  Upload,
  Share,
  Copy,
  ExternalLink,
  ArrowRight,
  ArrowLeft,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  X,
  Menu,
  MoreHorizontal,
  Play,
  Pause,
  Volume2,
  VolumeX,
  Wifi,
  WifiOff,
  Battery,
  BatteryLow,
  Signal,
  Bluetooth,
  Camera,
  Image,
  Video,
  Music,
  Headphones,
  Mic,
  MicOff,
  Bell,
  BellOff,
  MessageCircle,
  MessageSquare,
  Send,
  Bookmark,
  BookmarkCheck,
  Flag,
  Tag,
  Tags,
  Folder,
  FolderOpen,
  File,
  FileText,
  FileImage,
  FileVideo,
  Database,
  Server,
  Cloud,
  CloudDownload,
  CloudUpload,
  Network,
  Globe,
  Link,
  Unlink,
  Refresh,
  RotateCcw,
  RotateCw,
  Maximize,
  Minimize,
  Square,
  Circle,
  Triangle,
  Hexagon,
  Octagon,
  Diamond,
  Sparkles,
  Gamepad2
};

// Ícones específicos para gaming
export const GamingIcons = {
  Valorant: Target,
  CS2: Sword,
  FIFA: Trophy,
  Gaming: Gamepad2,
  Weapon: Sword,
  Skin: Sparkles,
  Rank: Crown,
  Premium: Gem,
  Exclusive: Diamond,
  Limited: Zap,
  Popular: Star,
  New: Gift
};

// Ícones para UI/UX
export const UIIcons = {
  Success: CheckCircle,
  Error: AlertCircle,
  Warning: AlertCircle,
  Info: Info,
  Loading: Clock,
  Close: X,
  Menu: Menu,
  Search: Search,
  Filter: Filter,
  Add: Plus,
  Remove: Minus,
  Edit: Edit,
  Delete: Trash2,
  View: Eye,
  Hide: EyeOff,
  Download: Download,
  Upload: Upload,
  Share: Share,
  Copy: Copy,
  External: ExternalLink
};

// Ícones para e-commerce
export const EcommerceIcons = {
  Cart: ShoppingCart,
  Wallet: Wallet,
  Payment: Wallet,
  Order: Package,
  Delivery: Package,
  Rating: Star,
  Review: MessageCircle,
  Wishlist: Heart,
  Discount: Tag,
  Sale: Flame,
  Premium: Crown,
  Security: Shield,
  Support: MessageCircle,
  Account: User
};